버전 2.1로 수정
hslee1024/BulDakLauncher pull request #9
Opened 2020-09-04 13:57 UTC by norhu1130

패치노트 등에 2.0 이라고 써있던데 2.1.0되서 2.1로바뀌었습니다.
(내 간지내놔아)

2020-09-05 01:51 UTC, choo5145 requested changes
welcome.ejs도 수정해주세요

2020-09-05 03:43 UTC, norhu1130 commented
확인하였습니다. 지금 패치 넣겠습니다.

2020-09-05 03:44 UTC, norhu1130 commented
커밋하였습니다.

2020-09-05 03:49 UTC, norhu1130 commented
@choo5145 지적 감사합니다

2020-09-05 05:32 UTC, choo5145 approved these changes
문제 없습니다

2020-09-06 14:40 UTC, merged

2020-09-06 14:40 UTC, hslee1024 commented
머지 하였습니다 감사합니다